### ISSUE TITLE
Informations about new versions

### ISSUE THREAD

**Issue by ClementGTHR** [sympa-community/sympa#1006]
Hello, 

I actually work for Ministry of Economy and Finance of the French Republic.
We’re using SYMPA mailing list for our newsletters. 
Actually, it run on V6.1.17 (pretty old I guess) 

We’re thinking about an upgrade to the V6.2.56.

Before we start the upgrade we’ll need to know what's new between V6.1.17 and 6.2.56. To know if it's really pragmatic. 

Can you tell me how to find these informations or maybe can you tell me overall what’s new ? 

By advance, thank you 

If you have any question, don’t hesitate 

Best regards

**Comment by ldidry** [comment]
Hello,

Wow! 6.1.17! You can read https://github.com/sympa-community/sympa/blob/sympa-6.2/NEWS.md, but it will take you some time 😅

I think that the main change you will immediately see is the new interface, but it sure is not the only thing.

There has been A LOT of changes since 6.1.17, I don’t know all of them (far from it), but one important thing is DKIM/DMARC handling.

Otherwise: bugs fixed, features added, minimal perl version update to 5.10.1.

**Comment by racke** [comment]
Moving owners and moderators from config file to the database was also a big change. You better test the migration in a development server (VM) before touching your live system.

**Comment by ClementGTHR** [comment]
Thank you guys ! 

I saw that there is a testing platform ( https://demo.sympa.org/sympa/home ) 
is it relevant ?

**Comment by ikedas** [comment]
@ClementGTHR ,
- Read [Upgrading Sympa](https://sympa-community.github.io/manual/upgrade.html),
- then read [Upgrading from Sympa 6.1.x or earlier](https://sympa-community.github.io/manual/upgrade/notes.html#upgrading-from-sympa-61x-or-earlier) to know consideration specific to 6.1.x.
- and [Upgrading from Sympa 6.2.x or earlier](https://sympa-community.github.io/manual/upgrade/notes.html#upgrading-from-sympa-62x-or-earlier) to know about recent changes.

As racke wrote, you'd be better to prepare development server by your own to test migration process.

**Comment by ikedas** [comment]
No more comments.  Close.
