### ISSUE TITLE
Error with modifying default header/footer template

### ISSUE THREAD

**Issue by privas89** [sympa-community/sympa#1057]
Hi all,

I'm currently experiencing a generic server error whenever I try to modify the header/default footer template. What's strange is that I'm able to update any other template. Here are my logs:

# Successful modification of unsubscribe template
Dec 15 14:46:50 rolodex wwsympa[12736]: debug3 Sympa::search_fullpath(lists.domain.com, bye.tt2, subdir)
Dec 15 14:46:50 rolodex wwsympa[12736]: debug3 Sympa::get_search_path(lists.domain.com, subdir, mail_tt2/)
Dec 15 14:46:50 rolodex wwsympa[12736]: debug3 Sympa::search_fullpath() Name: bye.tt2; file /etc/sympa/mail_tt2//bye.tt2

# Error when trying to modify the footer template
Dec 15 14:07:43 rolodex wwsympa[12733]: debug3 Sympa::search_fullpath(lists.domain.com, message_footer, subdir)
Dec 15 14:07:43 rolodex wwsympa[12733]: debug3 Sympa::get_search_path(lists.domain.com, subdir, )
Dec 15 14:07:43 rolodex wwsympa[12733]: err main::#1556 > main::do_editfile#8370 [robot lists.domain.com] [session 30666431499125] [client 10.27.210.10] [user admin@domain.com] Failed to open file : No such file or directory

My message_footer.tt2 file is located under /usr/share/sympa/default/web_tt2 but it can't seem to grab it. I've tried setting it under /etc/sympa/web_tt2 but I get the same error.

Any help would be greatly appreciated!

**Comment by ikedas** [comment]
Hi @privas89 , could you please show us:
- the version of Sympa,
- the operation step-by-step that you performed (e.g.: "Launched web browser, accessed to URL xxx, entered a text "xxx" into xxx textbox, clicked xxx button, ...).
- what was show in the display as a result of operation above (e.g. error message).

**Comment by privas89** [comment]
> Hi @privas89 , could you please show us these things?
> 
> * the version of Sympa,
> * the operation step-by-step that you performed (e.g.: "Launched web browser, accessed to URL xxx, entered a text "xxx" into xxx textbox, clicked xxx button, ...).
> * what was show in the display as a result of operation above (e.g. error message).

Hi @ikedas!

We are currently on V. 6.2.58.
We have SSO via SAML2 these are the steps with an in-cognito window:

1. Login with SAML.
2. Go to the listmaster admin section (https://server.domain.com/sympa/serveradmin)
3. Go to Templates section (https://server.domain.com/sympa/serveradmin/templates)
4. Select either 'message header' or 'mesage footer' from the dropdown menu from the 'Edit default list template' form.
5. Click on the 'edit' button to submit the form.

After hitting submit I get the following error "INTERNAL SERVER ERROR (editfile) -"

Thank you.

**Comment by ikedas** [comment]
@privas89 ,
> > * the operation step-by-step that you performed (e.g.: "Launched web browser, accessed to URL xxx, entered a text "xxx" into xxx textbox, clicked xxx button, ...).

You showed operation in the case of "message header"/"message footer".  Could you please also show the case of "bye.tt2"?

Additionally, could you please show the Sympa's log _from when_ you started the operation _to when_ error occured.
--- And at that time, please don't set `log_level` in `sympa.conf`: Debug logs are useful only for  development purpose, and in usual use they might hide the other useful logs.

**Comment by DrNatas** [comment]
This one is for the message footer. 

`Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::User::is_global_user(john.doe@domain.com)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::Database::do_prepared_query() Will perform query "SELECT COUNT(*) FROM user_table WHERE email_user = ?"
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::User::get_global_user(john.doe@domain.com)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::Database::do_prepared_query() Will perform query "SELECT email_user AS email, gecos_user AS gecos, password_user AS password, cookie_delay_user AS cookie_delay, lang_user AS lang, attributes_user AS attributes, data_user AS data, last_login_date_user AS last_login_date, wrong_login_count_user AS wrong_login_count, last_login_host_user AS last_login_host FROM user_table WHERE email_user = ?"
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 main::check_param_in() [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, create_list, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, create_list.public_listmaster, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: create_list.public_listmaster; file /usr/share/sympa/default/scenari/create_list.public_listmaster
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::authz(Sympa::Scenario <create_list.public_listmaster;/usr/share/sympa/default/scenari/create_list.public_listmaster>, md5, HASH, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::do_search(lists.domain.com, HASH, blacklist.txt)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, blacklist.txt, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, order, all)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 main::export_topics(lists.domain.com) [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Robot::load_topics(lists.domain.com)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, topics.conf, )
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, , )
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: topics.conf; file /etc/sympa/topics.conf
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: info main::do_editfile(message_footer) [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, message_footer, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, )
Dec 15 16:52:45 rolodex wwsympa[16507]: err main::#1556 > main::do_editfile#8370 [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com] Failed to open file : No such file or directory
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::send_notify_to_listmaster(lists.domain.com, web_intern_error, HASH)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Tools::SMIME::find_keys(lists.domain.com, sign)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Message::Template::_new_from_template(Sympa::Message::Template, lists.domain.com, listmaster_notification.tt2, ARRAY, HASH)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, include_path, ARRAY)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Message::new(Sympa::Message::Template, ...)
Dec 15 16:52:45 rolodex wwsympa[16507]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <sympa@lists.domain.com.1608079965.16507,3436>; envelope_sender=sympa-request@lists.domain.com; message_id=sympa.1608079965.16507.420@lists.domain.com; recipients=ARRAY; sender=sympa@lists.domain.com; template=listmaster_notification; type=web_intern_error; action=Command process
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: domain.com; rcpt by dom: 1; limit for this domain:
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: domain.com; rcpt by dom: 2; limit for this domain:
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: domain.com; rcpt by dom: 3; limit for this domain:
Dec 15 16:52:45 rolodex wwsympa[16507]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message::Template <sympa@lists.domain.com.1608079965.16507,3436> is stored into bulk spool as <1.5.1608079965.1608079965.409473.sympa@lists.domain.com_s,16507,8919>
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::Database::do_prepared_query() Will perform query "INSERT INTO logs_table (date_logs, usec_logs, robot_logs, list_logs, action_logs, parameters_logs, target_email_logs, msg_id_logs, status_logs, error_type_logs, user_email_logs, client_logs, daemon_logs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 main::prevent_visibility_bypass() [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com] Starting
Dec 15 16:52:45 rolodex wwsympa[16507]: debug2 main::check_param_out() [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]
Dec 15 16:52:45 rolodex wwsympa[16507]: debug Sympa::WWW::Session::store()
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::Database::do_prepared_query() Will perform query "SELECT id_session FROM session_table WHERE prev_id_session = ?"
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::Database::do_prepared_query() Will perform query "UPDATE session_table SET date_session = ?, remote_addr_session = ?, robot_session = ?, email_session = ?, start_date_session = ?, hit_session = ?, data_session = ? WHERE id_session = ? AND prev_id_session IS NOT NULL OR prev_id_session = ?"
Dec 15 16:52:45 rolodex wwsympa[16507]: debug Sympa::WWW::Session::set_cookie(Sympa::WWW::Session, localhost, 0, 1)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, css.tt2, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, subdir, web_tt2)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath() Name: css.tt2; file /usr/share/sympa/default/web_tt2/css.tt2
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::search_fullpath(lists.domain.com, css.tt2, subdir)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, lang_only, 1)
Dec 15 16:52:45 rolodex wwsympa[16507]: debug3 Sympa::get_search_path(lists.domain.com, include_path, ARRAY)
Dec 15 16:52:46 rolodex bulk[24234]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <1.5.1608079965.1608079965.409473.sympa@lists.domain.com_s,16507,8919/s> to lists.domain.com (priority 1) (starting 1 seconds after scheduled expedition date)
Dec 15 16:52:46 rolodex bulk[24234]: notice Sympa::Mailer::store() Done sending message Sympa::Message <1.5.1608079965.1608079965.409473.sympa@lists.domain.com_s,16507,8919/s> for lists.domain.com (priority 1) in 1 seconds since scheduled expedition date
`

This is one is for the bye.tt2
`Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::User::is_global_user(john.doe@domain.com)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::Database::do_prepared_query() Will perform query "SELECT COUNT(*) FROM user_table WHERE email_user = ?"
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::User::get_global_user(john.doe@domain.com)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::Database::do_prepared_query() Will perform query "SELECT email_user AS email, gecos_user AS gecos, password_user AS password, cookie_delay_user AS cookie_delay, lang_user AS lang, attributes_user AS attributes, data_user AS data, last_login_date_user AS last_login_date, wrong_login_count_user AS wrong_login_count, last_login_host_user AS last_login_host FROM user_table WHERE email_user = ?"
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 main::check_param_in() [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, create_list, ...) 
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, create_list.public_listmaster, subdir)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: create_list.public_listmaster; file /usr/share/sympa/default/scenari/create_list.public_listmaster
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::authz(Sympa::Scenario <create_list.public_listmaster;/usr/share/sympa/default/scenari/create_list.public_listmaster>, md5, HASH, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::do_search(lists.domain.com, HASH, blacklist.txt)       
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, blacklist.txt, subdir)         
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, order, all)                    
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 main::export_topics(lists.domain.com) [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Robot::load_topics(lists.domain.com)                             
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, topics.conf, )                 
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, , )                            
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: topics.conf; file /etc/sympa/topics.conf 
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::new(Sympa::Scenario, lists.domain.com, topics_visibility, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, topics_visibility.noconceal, subdir)
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, scenari)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: topics_visibility.noconceal; file /usr/share/sympa/default/scenari/topics_visibility.noconceal
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 Sympa::Scenario::authz(Sympa::Scenario <topics_visibility.noconceal;/usr/share/sympa/default/scenari/topics_visibility.noconceal>, md5, HASH, ...)
Dec 15 16:57:17 rolodex wwsympa[16505]: info main::do_editfile(bye.tt2) [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, bye.tt2, subdir)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, mail_tt2/)             
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: bye.tt2; file /etc/sympa/mail_tt2//bye.tt2 
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::Database::do_prepared_query() Will perform query "INSERT INTO logs_table (date_logs, usec_logs, robot_logs, list_logs, action_logs, parameters_logs, target_email_logs, msg_id_logs, status_logs, error_type_logs, user_email_logs, client_logs, daemon_logs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
Dec 15 16:57:17 rolodex wwsympa[16505]: debug2 main::check_param_out() [robot lists.domain.com] [session 18919403277092] [client 10.27.210.42] [user john.doe@domain.com]                                                               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug Sympa::WWW::Session::store()                                             
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::Database::do_prepared_query() Will perform query "SELECT id_session FROM session_table WHERE prev_id_session = ?"
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::Database::do_prepared_query() Will perform query "UPDATE session_table SET date_session = ?, remote_addr_session = ?, robot_session = ?, email_session = ?, start_date_session = ?, hit_session = ?, data_session = ? WHERE id_session = ? AND prev_id_session IS NOT NULL OR prev_id_session = ?"
Dec 15 16:57:17 rolodex wwsympa[16505]: debug Sympa::WWW::Session::set_cookie(Sympa::WWW::Session, localhost, 0, 1)    
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, css.tt2, subdir)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, subdir, web_tt2)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath() Name: css.tt2; file /usr/share/sympa/default/web_tt2/css.tt2
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::search_fullpath(lists.domain.com, css.tt2, subdir)               
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, lang_only, 1)                  
Dec 15 16:57:17 rolodex wwsympa[16505]: debug3 Sympa::get_search_path(lists.domain.com, include_path, ARRAY)
`

**Comment by ikedas** [comment]
Oh I was confused!
The names of files are `message_footer` and `message_header`, without extensions.  These paths may be `/etc/sympa/message_footer` and so on.

**Comment by DrNatas** [comment]
We had no idea why the  INTERNAL SERVER ERROR (editfile)  error keeps on displaying.  Not sure if the logs helped at all. 
Same issue is with the TEMPLATES --> EDIT DEFAULT LIST TEMPLATE:: "message footer", "message header"
TEMPLATES --> EDIT SITE-WIDE TEMPLATES :: "list creation request message" 

That's it. All the other templates work perfectly.

**Comment by ikedas** [comment]
Could you please rename `message_footer.tt2` to `message_footer` and so on?

**Comment by DrNatas** [comment]
Yeah, I'll give that a try. I left my office, but once I get there in the morning it will be the 1st thing I'll try out. Thank you for your time and feedback!

**Comment by ikedas** [comment]
I couldn't reproduce the problem you reported.
- Sympa's version is 6.2.59b.2.

---
> 1. Login with SAML.
Though I don't use SAML, I succeeded logging in with default user database.

> 2. Go to the listmaster admin section (https://server.domain.com/sympa/serveradmin)
> 3. Go to Templates section (https://server.domain.com/sympa/serveradmin/templates)
> 4. Select either 'message header' or 'mesage footer' from the dropdown menu from the 'Edit default list template' form.
> 5. Click on the 'edit' button to submit the form.

The content of `message_footer` was shown.

Then I edit the content and clicked "Save".  The message "``savefile: action completed``" was shown.

I confirmed the file in the disk was updated. --- Note: As I configure virtual domain, updated content was saved in `/etc/sympa/virtual.dom.ain/message_footer`.

**Comment by ldidry** [comment]
> My message_footer.tt2 file is located under /usr/share/sympa/default/web_tt2 but it can't seem to grab it. I've tried setting it under /etc/sympa/web_tt2 but I get the same error.

Shouldn’t the templates for mails be under `/usr/share/sympa/default/mail_tt2`? And customisations in `/etc/sympa/mail_tt2`?

**Comment by ikedas** [comment]
> > My message_footer.tt2 file is located under /usr/share/sympa/default/web_tt2 but it can't seem to grab it. I've tried setting it under /etc/sympa/web_tt2 but I get the same error.
> 
> Shouldn’t the templates for mails be under `/usr/share/sympa/default/mail_tt2`? And customisations in `/etc/sympa/mail_tt2`?

No, at least after 6.2.42.  Previously, the place of these files was messed, then moved to consistent places (and naming). See also #507.

**Comment by ldidry** [comment]
> See also #507.

Oh, now I remember, sorry :sweat_smile:

**Comment by DrNatas** [comment]
No, luck. We even upgraded to 6.2.59b 2. We even downloaded the repo from github and replaced all the files under /usr/share/sympa/default/web_tt2/* with the files downloaded from the repo. We also renamed message_footer.tt2 to message_footer, and others with issues  (with no .tt2 extensions) and restarted both sympa and wwsympa services and no luck.

**Comment by ikedas** [comment]
It may sound silly, but could you execute these and show the result?
``` bash
# cat /etc/sympa/message_footer
# cat /etc/sympa/list.domain.com/message_footer
```
And, if either or both of files above were readable, are they readable by user `sympa`?

**Comment by DrNatas** [comment]
@ikedas The files were not under /etc/sympa/
After we cloned the templates the message error disappeared. :+1: 
I changed ownership to Sympa with 644 ACL. 

[root@domain sympa]# cp /var/lib/sympa/list_data/digest-test/message_header .
I'll chat with @privas89  to mark this thread as closed.

**Comment by privas89** [comment]
Thank you @ikedas !!!
