### ISSUE TITLE
Remove undocumented backtick syntax in sympa.conf

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#1086]
Backtick syntax (`` `...` ``) in `sympa.conf` should be removed, because it allows to execute arbitrary code.

Note: that syntax has not been documented yet.

**Comment by racke** [comment]
Reported as Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980451

**Comment by ikedas** [comment]
Comes under #1009.

**Comment by racke** [comment]
Debian uses the backtick in the following fashion:
```
cookie	`/usr/bin/head -n1 /etc/sympa/cookie`
```
I can get rid of that, but my question is the cookie value needed at all with recent Sympa release? It is not listed in the skeleton sympa.conf shipped with Sympa.

@ikedas @dverdin Any comment appreciated.

**Comment by dverdin** [comment]
Hi @racke,

As far as I can see in the code, the cookie parameter is used:

(if it does not exist in the configuration, it is set to the empty string so it is useless for instances that never used it)

- in the creation of the initial temporary password (Sympa::tools::Password).
- In creating the checksum used for upgrade_send_spool.pl
- In computing the old password value in upgrade_sympa_password.pl
- In creating the attachment URL for archived messages.

So this parameter is close to disappear  - and good riddance.

However, as a lot of older instances use it, it will still be needed for upgrade purpose. Otherwise, passwords might be lost while upgrading. And it will be needed for and undefinite time, except if we issue a release stating explicitely that passwords whould be requested by existing users- maybe not such a big deal if people are warned. Spools should also be totally empty before upgrade.

**Comment by racke** [comment]
Thanks a lot, @dverdin. So I only use the cookie parameter if present and leave it empty when installing Sympa Debian package for the first time.

**Comment by dverdin** [comment]
Yes. and that explains why it is not shipped with  Sympa anymore.

**Comment by racke** [comment]
OK so it is another spot in the documentation that needs to be filled.

**Comment by dverdin** [comment]
I can dot it if nobody disagrees.

**Comment by dverdin** [comment]
To have an up-to-date documentation, I need to change Sympa::Conf::Schema.

1. add "obsolete => 1," to the parameter description,
2. Modify the "gettext_comment" To add an explanation about precautions to take before removing it from the config file.

Afterwards, the gpldoc will be generated from the sources. Correct?

**Comment by racke** [comment]
Yes, but let's move that to a fresh issue.

**Comment by dverdin** [comment]
Separation of concerns. You're right.
I'll do a proposal.

**Comment by ikedas** [comment]
> Hi @racke,
> 
> As far as I can see in the code, the cookie parameter is used:

Your description is a bit inaccurate.

As far as I investigated with current stable (6.2.60), `cookie` parameter is used _at least_ in these things:

  - bin/upgrade_send_spool.pl#sympa_checksum()
    to migrate older bulk spool
    This is needed for upgrading from versions prior to 6.2.

  - bin/upgrade_sympa_password.pl#_decrypt_rc4_password()
    to migrate older user password
    This is needed for upgrading from versions prior to 6.2.26 by which RC4 encryption was deprecated.

  - Sympa::Tools::Password#tmp_passwd()
    to create temporary password for new users;
    This process should be removed after careful review.

  - Sympa::Archive#_get_tag()
    to generate randomized tags for `$tag$` notation in `mhonarc_ressources.tt2`
    This process should be removed by adopting another randomization.

  - Sympa::List.pm#get_cookie()
    to get List's (not the default in sympa.conf) `cookie` parameter
    This function is no longer used.

**Comment by ikedas** [comment]
> To have an up-to-date documentation, I need to change Sympa::Conf::Schema.

A step shoud be added:

  0. Modify codes that are using `cookie` parameter appropriately.

> 1. add "obsolete => 1," to the parameter description,
> 2. Modify the "gettext_comment" To add an explanation about precautions to take before removing it from the config file.
> 
> Afterwards, the gpldoc will be generated from the sources. Correct?

N.B. I suggest using [Task List](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to list todos in an issue.

**Comment by ikedas** [comment]
See #1091 for obsoletion of `cookie` parameter.

**Comment by dverdin** [comment]
Thanks for all these precisions @ikedas !
I'll use Task List when making todos. Thanks for the tip.

**Comment by mitar** [comment]
I am upgrading to a new version of Sympa and I am really sad to see this go. I was using this through `cat ...` for `db_passwd` so that the password is not stored in the main file (which can then be baked in into a public Docker image while the password can be then provided at container runtime).

I do not see any alternatives here? Sympa does not support config file includes? So I agree that supporting arbitrary commands it not reasonable, but being able to split config file into smaller files, including them from a directory like `sympa.conf.d` would be great. Am I right that this is not supported currently?

**Comment by mitar** [comment]
I see that there is old issue #17 which is still open, while this feature was removed. So there is no workaround. :-(
