### ISSUE TITLE
www.sympa.org does not send intermediate TLS certificate

### ISSUE THREAD

**Issue by scfc** [sympa-community/sympa#1131]
While checking URLs with curl/LWP, I noticed that https://www.sympa.org/ is not accessible due to a certificate error:

    [tim@passepartout ~]$ curl https://www.sympa.org/
    curl: (60) SSL certificate problem: unable to get local issuer certificate
    More details here: https://curl.haxx.se/docs/sslcerts.html
    
    curl failed to verify the legitimacy of the server and therefore could not
    establish a secure connection to it. To learn more about this situation and
    how to fix it, please visit the web page mentioned above.
    [tim@passepartout ~]$

This is due to the webserver only sending its own certificate, but not also the certificate for GEANT OV RSA CA 4 (cf. for example https://www.ssllabs.com/ssltest/analyze.html?d=www.sympa.org).  Interactive browsers will often magically download the missing chain elements, but this does not work for curl & Co.

It would be very nice if the webserver could be configured to send the intermediate certificate along as well.

**Comment by ikedas** [comment]
We don't have control on www.sympa.org server.  I'll forward your report to the administrator.  Thanks!

**Comment by dverdin** [comment]
It was a configuration error : when the *.sympa.org certificate was renewed, last months, the certificate authority was changed, too (because the certificate provider changed).
But we forgot to change the intermediate certificate. the problem did not appear at once because, most of the time, web browsers enrich their on certificate store themselves. Only curl - or an empty profile - could reveal it.

Sorry for the mess, it should be fixed by now.

Cheers!
