### ISSUE TITLE
Spam and list 100% error

### ISSUE THREAD

**Issue by titou3as** [sympa-community/sympa#1166]
After upgrading to a new server with Sympa 6.2.40, 
i have some public lists with 1 member into 100%error.
The code of member error is 5.7.1
These lists receive much spam.
How can i solve it , if it's possible.
Thank you for your response

**Comment by khaoula-abaidi** [comment]
Sympa : 6.2.40
Postfix: 3.4.13
Mysql : Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64
Ubuntu : Linux version 5.4.0-71-generic 
The lists concerned : visibility (conceal), send(public) with 1 subscriber
The problem is that the list receive too much spams per day a,d the error for the subscriber is : 
Final-Recipient: rfc822; xxxx@yyyy.fr
Original-Recipient: rfc822;xxxx@yyyy.fr
Action: failed
Status: 5.7.1
Remote-MTA: dns; mxd.relay.zzzz.fr
Diagnostic-Code: smtp; 550 5.7.1 Policy reason

Is there any command line to add into sympa.conf to limit the spams for example or a configuration to public lists.

**Comment by khaoula-abaidi** [comment]
> Do you have a spam filter and virus scanner which checks incoming email?

No , i haven't

**Comment by racke** [comment]
You definitely need it to prevent SPAM entering your list. But I think it is off topic in a Sympa issue.

**Comment by ikedas** [comment]
No more conversation.  Close for now.

**Comment by elchusco** [comment]
Hi,

Actually I am facing the same issue. I do have  both antispam (SA) and antivirus (ClamAV) filteringmy incoming mails. But still, some spams may pass through. In my opinion a mail address shouldn't be marked as bouncing if the SMTP error code is "5.7.1 Policy reason" because it doesn't mean the mailbox is unreachable but only that this specific mail is not allowed by the remote server. 

It seems impossible to guess which message would be allowed by a remote antispam software.

What's your opinion on the matter ?
