### ISSUE TITLE
Enabling SSO on starting page

### ISSUE THREAD

**Issue by jaspis259** [sympa-community/sympa#1225]
Hello,

I would like to put behind SSO all parts of Sympa `/sympa` (including starting page).
I managed to configure Sympa to use SSO using Apache + OpenID (https://github.com/zmartzone/mod_auth_openidc/blob/v2.3.11/auth_openidc.conf#L614)

Below part of Apache configuration

  <Location "/sympa">
    Require valid-user
    AuthType openid-connect
    SetHandler proxy:unix:/var/run/sympa/wwsympa.socket|fcgi://
  </Location>
  <Location "/sympa/sso_login/cernsso">
    Require valid-user
    AuthType openid-connect
	SetHandler proxy:unix:/var/run/sympa/wwsympa.socket|fcgi://
  </Location>

Problem is that when I access `\sympa` Sympa is not aware that SSO was performed and doesn't display my e-mail address in top right corner. It displays a button to perform login "SSO Login". Also logs doesn't show my e-mail address for initiated requests. Only when I click on a button to login, my e-mail address is shown (it works without redirection to SSO page because I was already authenticated so Sympa does have my token). After clicking on "SSO Login" I can manage my lists and in logs I can see my e-mail address as a user that initiates requests. 

Is there a configuration that I'm missing that would allow users to be fully authenticated on main/starting page after performing SSO login?

BTW: everything works properly if I click button "SSO login" or I access URL: https://example.com/sympa/sso_login/cernsso/init. 

Thanks for the hints. 
Pawel

Version
-------
Sympa 6.2.62 on CENTOS 7

Installation method
-------------------
RPM

Expected behavior
-----------------
Sympa web portal performs authentication and retrieves e-mail address of logged person on start/main page.

Actual behavior
---------------
Sympa web portal performs authentication and retrieves e-mail address after clicking on "SSO Login" button OR after visiting URL:  https://example.com/sympa/sso_login/cernsso/init

**Comment by ikedas** [comment]
Hi @jaspis259 ,

> Hello,
> 
> I would like to put behind SSO all parts of Sympa `/sympa` (including starting page).
> I managed to configure Sympa to use SSO using Apache + OpenID (https://github.com/zmartzone/mod_auth_openidc/blob/v2.3.11/auth_openidc.conf#L614)
> 
> Below part of Apache configuration
> 
> <Location "/sympa">
> Require valid-user
> AuthType openid-connect
> SetHandler proxy:unix:/var/run/sympa/wwsympa.socket|fcgi://
> 
> <Location "/sympa/sso_login/cernsso">
> Require valid-user
> AuthType openid-connect
> SetHandler proxy:unix:/var/run/sympa/wwsympa.socket|fcgi://

I guess _not both of_ these `<Location>` sections are necessary, as I describe in below.

> Problem is that when I access `\sympa` Sympa is not aware that SSO was performed and doesn't display my e-mail address in top right corner. It displays a button to perform login "SSO Login". Also logs doesn't show my e-mail address for initiated requests. Only when I click on a button to login, my e-mail address is shown (it works without redirection to SSO page because I was already authenticated so Sympa does have my token). After clicking on "SSO Login" I can manage my lists and in logs I can see my e-mail address as a user that initiates requests.

It's expected behavior.  Sympa does not always contact with SSO:
  1. When the user clicks "SSO Login" button at the first time, Sympa redirects them to `https://example.com/sympa/sso_login/<service_id>/init`.
     (Note that, in this step, this URL does not perform any function of Sympa: See the next step.)
  2. SSO intercepts this access and redirects to authetication page provided by it.
  3. The user authenticates.
  4. (SSO may redirect to the page in below again, if it can do.)
  5. Again, when the user accesses to `https://example.com/sympa/sso_login/<service_id>/init`,  Sympa gets user information passed by SSO and caches them.
  6. Hereafter, Sympa identifies the information above with the user, using HTTP cookie issued by Sympa itself.

Essentially, Sympa cantacts with SSO only at the step 5.

> Is there a configuration that I'm missing that would allow users to be fully authenticated on main/starting page after performing SSO login?
> 
> BTW: everything works properly if I click button "SSO login" or I access URL: https://example.com/sympa/sso_login/cernsso/init.

It's possible if you realize the step 4. above, i.e. configuring SSO to redirect to `https://example.com/sympa/sso_login/<service_id>/init` after successful authentication.

If you want further information, please show us the configuration of your Sympa (`auth.conf`) and OpenID software.

**Comment by ikedas** [comment]
No more questions.  Close.
