### ISSUE TITLE
Question about implementation of sympa rpm in Epel 8

### ISSUE THREAD

**Issue by MorenoUniTN** [sympa-community/sympa#1346]
Hi all,
we wuold ask you if there are news to implementation the package rmp of SYmpa in Epel 8.
Now the rpm is only aviable on Epel 7 and with the end of live of CentOS 7 we need to migrate our server linux RedHat 8 based (AlmaLinux or RockLinux) with Epel 8.

Thanks in advanced for the asnwere.
Hi all,

**Comment by ikedas** [comment]
Sympa package for EPEL 8 looks [planned](https://bugzilla.redhat.com/show_bug.cgi?id=1749385) now.  @xavierba , is there anything to do to make the package available?

**Comment by xavierba** [comment]
Sympa for EPEL 8 is ready for quite some time now, and EPEL 9 is ready too.
Actually, Sympa for EL8 is available in my COPR repo at https://copr.fedorainfracloud.org/coprs/xavierb/sympa/. Sympa for EL9 is not, because spaw-fcgi is missing, see below.

The last open question is around the use of spawn-fcgi versus systemd sockets and multiwatch, as discussed in https://github.com/sympa-community/sympa/issues/799. @ikedas, I'd be grateful if you could take another look at the proposal and also if @racke could compare with what he has done for Debian, so we can unify the implementation.

**Comment by xavierba** [comment]
The COPR repo needs EPEL, and EPEL needs CRB/powertools repo, which is not enabled by default.
See https://docs.fedoraproject.org/en-US/epel/#_quickstart

**Comment by LoserFriendly** [comment]
> The COPR repo needs EPEL, and EPEL needs CRB/powertools repo, which is not enabled by default. See https://docs.fedoraproject.org/en-US/epel/#_quickstart

Thank you very much, problem solved. I hadn't enabled powertools, but EPEL only.

**Comment by MorenoUniTN** [comment]
Hi @ikedas @xavierba,
we installed on our server Xavier's COPR repository for installing sympa in RHEL 8.6 and we have installed the currently available version 6.2.68.

We would like to ask if sympa 6.2.70 and future verions will be added to Xavier's COPR repository?

Thanks in advance

**Comment by xavierba** [comment]
Sympa for EL8 and EL9 will be available from the EPEL repository from now on, just like it is already for Fedora and EL7. 
https://bodhi.fedoraproject.org/updates/?packages=sympa
Sympa 6.2.70 is going to be pushed to the testing repositories in the next few hours.
Not sure if I'll still make use of the COPR repo, most probably not.
