### ISSUE TITLE
Messages with list address in the "From:" header or FROM envelope should be rejected by default

### ISSUE THREAD

**Issue by vinc17fr** [sympa-community/sympa#1506]
Expected Behavior
-----------------
Since messages posted to a mailing-list should never have a "From:" set to the list address, such messages should be rejected by default.

Current Behavior
----------------
Such messages are currently accepted, even in moderated lists (so this is an easy way for spammers to bypass moderation).

Possible Solution
-----------------
Reject such messages unconditionally. The reject should be based on the "From:" header, and possibly on the FROM envelope.

Context
-------
Spammers sometimes use a "From:" address set as the same as the "To:" address. I've seen at least 2 mailing-lists managed by Sympa (the GNU MPFR mailing-list, which is public and moderated; and a private list internal to my lab) where this occurred.

**Comment by ikedas** [comment]
There can be use cases where legitimate users send emails with the `From:` field as a list address, so IMO they shouldn't be prohibited uniformly.

Using the scenario, posts from non-subscribers may be discarded ([`send.confidential`](https://github.com/sympa-community/sympa/blob/6.2.68/default/scenari/send.confidential)), rejected ([`send.private`](https://github.com/sympa-community/sympa/blob/6.2.68/default/scenari/send.private)) or held for moderation ([`send.privateoreditorkey`](https://github.com/sympa-community/sympa/blob/6.2.68/default/scenari/send.privateoreditorkey)).

**Comment by vinc17fr** [comment]
Then there should be an option so that messages posted with the list address in the `From:` header are rejected.

I don't understand what you intend to mean by "posts from non-subscribers". The fact is that the list address is regarded by Sympa as a subscriber. So one would need to a scenario to specifically reject messages whose sender is the list address. I suppose that if `match` supports variables and the list address is available as a variable, this could be done, but neither is [documented](https://www.sympa.community/manual/customize/basics-scenarios.html).

**Comment by ikedas** [comment]
> I don't understand what you intend to mean by "posts from non-subscribers". The fact is that the list address is regarded by Sympa as a subscriber. So one would need to a scenario to specifically reject messages whose sender is the list address. I suppose that if `match` supports variables and the list address is available as a variable, this could be done, but neither is [documented](https://www.sympa.community/manual/customize/basics-scenarios.html).

I think the address that is same as the list address may not be a subscriber of that list itself.

**Comment by ldidry** [comment]
> There can be use cases where legitimate users send emails with the From: field as a list address, so IMO they shouldn't be prohibited uniformly.

Indeed : there is some mails I send to some people from the address of a mailing list, BCC the ML, to be sure that the people I write to respond to the same address (yes, I know the Reply-To header, but people **always** find a way to do something weird if you let them the tiniest way to do it).

To forbid the `From: ML`, you should use spf/dkim/dmarc and an antispam configured to refuse mails with bad spf/dkim behavior. That’s what I do (I can still send mails with `From: ML` because I send them from authorized servers).

**Comment by vinc17fr** [comment]
Using spf/dkim/dmarc seems overkill (unless you have a simple configuration to do that - note that it must not prevent other messages from being posted, even with bad spf/dkim, as this sometimes occurs for legitimate mail messages). Why isn't there a way to just reject `From: ML` messages?

**Comment by ikedas** [comment]
I understand the list [mpfr](https://sympa.inria.fr/sympa/arc/mpfr) is the discussion list.  Don't you restrict posts from non-subscribers?  I wonder, if you had not done so, the list would receive spam with any `From:`, not only the list address.

**Comment by vinc17fr** [comment]
Posts from subscribers are automatically accepted, but posts from non-subscribers are moderated (the moderators accept or reject the message). So the list normally does not get spam. But the message with `From: ML` was accepted without the moderation step.

**Comment by ikedas** [comment]
@vinc17fr , I couldn't reproduce the problem you described on Sympa 6.2.68.  Steps to reproduce are:
  1. Set "send" scenario as `privateoreditorkey` so that the posts are restricted only for subscribers.
  2. Send a message to a list with `From:` field as the address of the list itself.

Result is:
  * The message was held for moderation.
  * Moderation notification was sent to the list moderators (in my case they are the same as owners).
  * Moderation notification to the sender was sent to the list address.  However, it was ignored according to [`loop_prevention_regex`](https://www.sympa.community/gpldoc/man/sympa_config.5.html#loop_prevention_regex) setting and wasn't deliverred to the list.

Can you check these things?
  1. How the "send" scenario is configured on your list?  Below is an example.
    ![image](https://user-images.githubusercontent.com/5743546/198814386-f9c85e75-be88-46c2-996c-40d23f60bf44.png)
       * If your list uses customized scenario, please show its source too.
  3. Isn't the list address a subscriber of the list itself? Please review the subscribers.
  4. Isn't the list address a moderator or an owner of the list itself? (The scenario in the example above also allows posts from the moderators.)  Please review the moderators and owners.
  5. Please show the log _from when_ the message in the proglem was postsed _to when_ it had been successfully delivered.

**Comment by vinc17fr** [comment]
After a discussion, it appeared that the MPFR list is actually using a local scenario that allows all senders from INRIA domains, which explains the issue since the list is hosted by an INRIA domain. Such a scenario is probably not a good idea (and I'm wondering why it is used for this list).

**Comment by ikedas** [comment]
OKey, if you think this issue is solved, please tap [close] button.  I thank you for sharing your experiences.

**Comment by vinc17fr** [comment]
OK, let's consider it as solved.
