### ISSUE TITLE
Limit spam when database isn't accessible

### ISSUE THREAD

**Issue by etienne02** [sympa-community/sympa#158]
Hi,

When the database is not accessible by sympa, sympa send hundreds of mails per minute, until the problem is solved. Is it possible to change this behaviour ? For instance sending two mails, one when the problem appears and one when the problem is solved.

Thank you.

**Comment by racke** [comment]
I never got that many emails from Sympa when the database was unaccessible, but still too much emails.

**Comment by ikedas** [comment]
Hi @etienne02,

At least with recent version, Sympa behaves like you wrote: *sending two mails, one when the problem appears and one when the problem is solved*.  One have subject "No DataBase" and another have "DataBase connection restored". 

If you receive these two messages frequently, there can be some problem on connection between Sympa server and database server.  How about consulting administrator of servers or (if separate database server is used) network administrator?

**Comment by etienne02** [comment]
My sympa version was the debian jessie version. Since i updated to the debian stretch version, it is probably fixed now. Thanks, i close the issue.
