### ISSUE TITLE
The ability to add an addition owner on the create_list_request.tt2

### ISSUE THREAD

**Issue by Ne-34** [sympa-community/sympa#1781]
We would like to require a user that is using the sympa web interface to create a list, to have two owners on the create_list_request form in order for the list to be created. How can we achieve that?

I know that users can add additional owners after the list has been created. We would like to make two owner mandatory on the form before the list is created.

Version
-------

Sympa Version 6.2.72

Installation method
-------------------

Source package

Expected behavior
-----------------

Actual behavior
---------------

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @Ne-34 ,

You can add `custom_input` field(s) so that custom parameters entered in web form may be passed to the list creation templates.

1.  Add a form field with a name `custom_input.ANYTHING` to `web_tt2/create_list_request.tt2`,  e.g.:
    ```html
    <label for="additional_owner">Additional Owner:</label>
    <input type="email" id="additional_owner" name="custom_input.additional_owner">
    ```
2.  Add the custom parameter to `config.tt2` file in the list creation template, e.g.:
    ```code
    [% IF custom_input.additional_owner %]
    owner
      email [% custom_input.additional_owner %]
    
    [%END%]
    ```

* For details on customization of templates see [the manual](https://www.sympa.community/manual/customize/basics-templates.html).

Then the field "Additional Owner" appears in the list creation request form and both original and additional owners will be added to the resulting list.

**Comment by ikedas** [comment]
No further questions.  Close.
