### ISSUE TITLE
Deleted directory in archive folder never get cleaned

### ISSUE THREAD

**Issue by ydelattre** [sympa-community/sympa#1897]
Version
-------
6.2.68

Installation method
-------------------
deb

Expected behavior
-----------------
Archived emails deleted by the user, with "Tag messages for deletion", via the web interface, are deleted.

Actual behavior
---------------
Archived emails deleted by the user, with "Tag messages for deletion", via the web interface, are moved to a directory called "deleted" (sympa/arc/<liste_name>/AAA-MM/deleted). It seems that this folder never get cleaned.
This poses a problem because this folder is counted in the archive quota calculation, so a user can empty list archives with this method and still have an archive overquota.

Steps to reproduce
------------------
- have a list with some archives
- delete all archive from a month with the web interface and "Tag messages for deletion"
- navigate to the arc folder of this list
- notice that the folder month is still here and have a deleted folder with all email archive deleted.

Additional information
----------------------

**Comment by ikedas** [comment]
That's right.  Deleted messages are only moved to the `deleted` subdirectory and not really expunged.

I personally suppose (I don't know why it is) it may have some advantages as following:

* To be able to recover messages that have been accidentally deleted by users' operations.
* Messages that have been temporarily withheld for legal or other reasons can be restored when the problem is resolved.

---
Messages moved into `delete` directory may be deleted safely while web service is running.  To restore deleted messages you may have to move them onto original directory and rebuild archives.

**Comment by ydelattre** [comment]
Thanks for your prompt answer.
The problem is : we had a user who received an alert because the list archive was almost full.
He deleted all his list archive with this method and was confused because he was still getting the alert.

Also, if a user delete his list archive month by month (from Admin -> Manage Archives), all the archive folder is deleted without "backup".
There are 2 ways to delete an archive and the deletion is not done in the same way 🤔 

Don't know if it's something possible : add a button "purge archive" in [Admin] -> [Manage Archive] panel, 
Or a new checkbox "Permanently delete this mail" in the confirmation page after clicking the "tag this mail for deletion" button

Thanks a lot !
Yoann

**Comment by ikedas** [comment]
> Thanks for your prompt answer. The problem is : we had a user who received an alert because the list archive was almost full. He deleted all his list archive with this method and was confused because he was still getting the alert.
> 
> Also, if a user delete his list archive month by month (from Admin -> Manage Archives), all the archive folder is deleted without "backup". There are 2 ways to delete an archive and the deletion is not done in the same way 🤔

The user should have gotten the ZIP archive for the month they deleted.  Can you ask them to check the Download folder on their computer?

> Don't know if it's something possible : add a button "purge archive" in [Admin] -> [Manage Archive] panel, Or a new checkbox "Permanently delete this mail" in the confirmation page after clicking the "tag this mail for deletion" button


I personally think that, as I wrote in above, purging (permanently deleting) archives is highly risky and it would be better not to allow this feature to the owner.

> Thanks a lot ! Yoann

**Comment by ydelattre** [comment]
You're right. When a month is deleted, a zip archive is downloaded with all the archives of that month.
But the first problem remains :

> we had a user who received an alert because the list archive was almost full. He deleted all his list archive with this method and was confused because he was still getting the alert.

My first thought was : just permanently delete the file and the problem is solved. But as you say be able to recover message is important.
So, is there a way to not take the deleted folder into account in the quota archive ?

Thanks.
Yoann.

**Comment by ikedas** [comment]
It is not a reasonable decision not to count those moved to the `deleted` directory in the actual disk usage: From point of view of system admins, the amount of disk usage cannot be estimated correctly.

If you wish to stop the unlimited increase of disk usage by list archives, you'd be better to limit the archive retention period by setting [`archive.max_month`](https://www.sympa.community/gpldoc/man/sympa_config.5.html#archivemax_month) parameter to some or all lists, instead of expecting users to delete them voluntarily.

**Comment by ydelattre** [comment]
Ok. Will do that. 👍 
Thank you very much for all your answers and your time.

Yoann
