### ISSUE TITLE
How to disable annoying membership reminders as regular user?

### ISSUE THREAD

**Issue by darkdragon-001** [sympa-community/sympa#360]
I can't find an option to disable annoying membership reminders for the lists on my university mailing list server. 

This is how my configuration interface looks like. 
![mailing-list-options](https://user-images.githubusercontent.com/177976/42134338-4b43791a-7d3a-11e8-89fa-6b7e738d0978.png)

I think every user should have to ability to control which e-mails one wants to receive regardless of which settings administrators set.

**Comment by ikedas** [comment]
Hi @darkdragon-001,

Currently, subscription reminder cannot be disabled by each subscriber.

For the present, list owners can (1) disable subscription reminder at all, or (2) less frequent period (see configuration options below).

![sympa-6 2 33b 2-remind_task](https://user-images.githubusercontent.com/5743546/42200905-5c4ed51e-7ed0-11e8-8c37-7f659b0a9554.png)

On some sites the listmasters may hide the option above so that owners may not change this setting.  If it is the case, please ask owners to ask listmasters for changes.

**Comment by ikedas** [comment]
There seem no more answers. Close.
