### ISSUE TITLE
no-message_id problems.

### ISSUE THREAD

**Issue by CorneliusC** [sympa-community/sympa#576]
Hi,
we have the general problem, that multiple hosts and appliances send system-messages without an message-id. We can't solve this problem because there are too many different people and systems involved and Sympa reject these mails as I understand.

So I did a workaround for this, for example in file: 
.../sympa/bin/Spindle/ProcessIncoming.pm

**original file line 106**
```perl
unless (defined $message->{'message_id'}
        and length $message->{'message_id'}) {
        $log->syslog('err', 'Message %s has no message ID', $message);
        $log->db_log(
            #'robot'        => $robot,
            #'list'         => $listname,
            'action'       => 'process_message',
            'parameters'   => $message->get_id,
            'target_email' => "",
            'msg_id'       => "",
            'status'       => 'error',
            'error_type'   => 'no_message_id',
            'user_email'   => $message->{'sender'}
        );
        return undef;
    }
    my $msg_id = $message->{message_id};
```    

**my edited file on line 79**
```perl
   my $noidcheck = $message->{message_id};
   
    if ($noidcheck eq "") {
    my $randomnumber= int(rand(10000000000000));
    $noidcheck = $randomnumber;
        $log->db_log(
            #'robot'        => $robot,
            #'list'         => $listname,
            'action'       => 'process_message',
            'parameters'   => $message->get_id,
            'target_email' => "",
            'msg_id'       => "",
            'status'       => 'error',
            'error_type'   => 'no_message_id',
            'user_email'   => $message->{'sender'}
            );
    }
    my $msg_id = $noidcheck;
```
----------------------------------------------------------

It's maybe not the purpose for this whole thing,
but the messages has to be delivered and thats how
it works fine for us.

I repeated this random-id generation in this files:
DoForward.pm
DoMessage.pm
ProcessAutomatic.pm
ProcessBounce.pm
ProcessIncoming.pm

I don't know if other people have the same problems,
especially with hard to change out-of-the-box appliances
or older systems which just don't generate an message-id.

Maybe I could be a future feature to generate an message-id,
but it could also be a bad idea? What do you guys think?

**Comment by ikedas** [comment]
Hi @CorneliusC,
What MTA are you using with Sympa? And how do you configured the MTA for Sympa?

**Comment by CorneliusC** [comment]
That's a bit a tricky question. We have a central mail-backbone with several MTAs which delivers the mails to the sympa servers. On the sympa hosts we use postfix with an for sympa customized configuration. None of the systems do message-id checks. The mails will be just straight directed to sympa and sympa send the mails back to the backbone.

**Comment by ikedas** [comment]
Though I haven’t confirmed, you could set always_add_missing_headers (and maybe related parameters like local_header_rewrite_clients).  Please see postconf(5) for details.

**Comment by CorneliusC** [comment]
Thank you! I will check and test this. Maybe this will solve the problem better.

**Comment by ldidry** [comment]
@CorneliusC Did it fix your problem?

**Comment by djzhh** [comment]
Hi there,

this hits us too, esp. with e-mails from the outside. Using the workaround and adding the headers with Postfix breaks DMARC, as the Message-ID is added, where it is normally to be found within the DKIM-signed part.

Anyhow: as RFC 5322 states in "3.6. Field Definitions" (table) message-id: min number 0* SHOULD be present, this is definitely not a MUST have field, thus SYMPA cannot require it. So I assume, SYMPA's behaviour moving the e-mail to the bad queue should be considered as a bug.

**Comment by ikedas** [comment]
@djzhh , what MTA are you using with Sympa?

**Comment by ikedas** [comment]
> this hits us too, esp. with e-mails from the outside. Using the workaround and adding the headers with Postfix breaks DMARC, as the Message-ID is added, where it is normally to be found within the DKIM-signed part.

That seems odd. Are you saying that that outside organization has a good reason not to have a message ID in the message and is signing the null message ID field? I don't think so. I think, actually, they just may have an incomplete implementation that sends out messages without a message ID.

Also please read the discussion below.

> Anyhow: as RFC 5322 states in "3.6. Field Definitions" (table) message-id: min number 0* SHOULD be present, this is definitely not a MUST have field, thus SYMPA cannot require it. 

The RFC says
> An asterisk ("*") next to a value in the minimum or maximum column indicates that a special restriction appears in the Notes column.

then in the Note
>  SHOULD be present - see 3.6.4

and in 3.6.4
> Though listed as optional in the table in section 3.6, every message SHOULD have a "Message-ID:" field.

By the way, SHOULD is not the antonym of MUST as you claim, but RFC 2119 says
> 3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

Does the **valid reasons to ignore** recommendation in RFC 5322 3.6.4, that "every message SHOULD have a "Message-ID:" field", exist in your circumstances?  If that reason is a universal problem with Sympa's operations, then Sympa should address it.  If, on the other hand,  there is no such reason, then you or someone should fix the _im_**perfect implementation** that is ignoring the recomendations.

If you can't fix it, then all you can do on your end is to override the DMARC policy provided by the sender with a local policy so that the message can be received by your organization.

**Comment by djzhh** [comment]
Dear IKEDA Soji,

Thanks a lot for your answer. While I understand your arguments in principal,
it is just not feasible to enter discussion with every sender if or if
not there is a "valid reason" to ignore the recommendation, as it is still
up to the sender's decision. And in case there would be such a valid reason,
may one expect that such e-mails are processed or might one of the "full
implications" be, that such e-mails would not be accepted everywhere?

This is in no way a complaint, more something to consider in general.

We will most probably configure Postfix on our SYMPA MTA to add the missing
Message-ID and handle the potential DKIM problems as well as contacting
the sender, which is a service provider for governmental IT services,
hoping that they have a chance to correct this.

Best regards,
Dirk

**Comment by racke** [comment]
My two cents: Aside from the RFC theory it doesn't make sense to accept emails with such defects.

**Comment by quenenni** [comment]
Hello,

I have a quite simple instance of Sympa with few lists (postfix as MTA).
All the lists work perfectly except for 1 person in 1 list (with a fastmail.fm address, the only one I found).

I checked the logs and all received mails have a message-id except the one from fastmail.

From what I read in this post, is the solution from @CorneliusC a good one or is it bad and better ask the person to either contact its mail provider to ask to fix this message-id problem (or swtich to another mail provider)?

Can this empty message-id be used to do bad things (and so the fix proposed can bring dangerous situation)?

**Comment by ikedas** [comment]
Hi @quenenni ,

> Can this empty message-id be used to do bad things (and so the fix proposed can bring dangerous situation)?

Sympa discards and does never process messages that do not have Message-ID field, because It has been known that such messages cannot be processed correctly.

If you decided that you must receive certain messages that do not have message ID, you may want to take any measures (solutions). Otherwise, you may not necessarily take measures and let Sympa discard them.
