### ISSUE TITLE
Structure of list alias template list_aliases.tt2

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#739]
The structure of the list alias email looks odd to me for the case that we have multiple domains:

```
[% list.domain %]-[% list.name %]: "| --libexecdir--/queue [% list.name %]@[% list.domain %]"
[% list.domain %]-[% list.name %]-request: "| --libexecdir--/queue [% list.name %]-request@[% list.domain %]"
[% list.domain %]-[% list.name %]-editor: "| --libexecdir--/queue [% list.name %]-editor@[% list.domain %]"
#[% list.domain %]-[% list.name %]-subscribe: "| --libexecdir--/queue [% list.name %]-subscribe@[% list.domain %]"
[% list.domain %]-[% list.name %]-unsubscribe: "| --libexecdir--/queue [% list.name %]-unsubscribe@[% list.domain %]"
[% list.domain %]-[% list.name %][% return_path_suffix %]: "| --libexecdir--/bouncequeue [% list.name %]@[% list.domain %]"
```
I would rather expect `[% list.name %]@[% list.domain %]`.  Can anyone shed a light on that?

BTW for my Exim setup I use the aliases without the domain, but using a different alias file for each domain. The location is set in the robot.conf like that:

```
sendmail_aliases /etc/mail/sympa/post.perl.dance

```

The alias template:

```
#------------------------------ [% list.name %]: list alias created [% date %]
[% list.name %]: "| /usr/lib/sympa/bin/queue [% list.name %]@[% list.domain %]"
[% list.name %]-request: "| /usr/lib/sympa/bin/queue [% list.name %]-request@[% list.domain %]"
[% list.name %]-editor: "| /usr/lib/sympa/bin/queue [% list.name %]-editor@[% list.domain %]"
#[% list.name %]-subscribe: "| /usr/lib/sympa/bin/queue [% list.name %]-subscribe@[% list.domain %]"
[% list.name %]-unsubscribe: "| /usr/lib/sympa/bin/queue [% list.name %]-unsubscribe@[% list.domain %]"
[% list.name %][% return_path_suffix %]: "| /usr/lib/sympa/bin/bouncequeue [% list.name %]@[% list.domain %]"

```

**Comment by racke** [comment]
In our Ansible project we install a [custom alias template](https://github.com/sympa-community/sympa-ansible/blob/master/roles/sympa/files/list_aliases.tt2) which uses @ for the alias email address:

```
#--- [% list.name %]@[% list.domain %]: list transport map created at [% date %]
[% list.name %]@[% list.domain %] sympa:[% list.name %]@[% list.domain %]
[% list.name %]-request@[% list.domain %] sympa:[% list.name %]-request@[% list.domain %]
[% list.name %]-editor@[% list.domain %] sympa:[% list.name %]-editor@[% list.domain %]
#[% list.name %]-subscribe@[% list.domain %] sympa:[% list.name %]-subscribe@[%list.domain %]
[% list.name %]-unsubscribe@[% list.domain %] sympa:[% list.name %]-unsubscribe@[% list.domain %]
[% list.name %][% return_path_suffix %]@[% list.domain %] sympabounce:[% list.name %]@[% list.domain %]
```

**Comment by ikedas** [comment]
The [first excerpt](https://github.com/sympa-community/sympa/issues/739#issue-487773155) is a trick for Sendmail which essentially can*not* handle virtual domains (but only determins recipients by local parts).
Adding this line to `virtusertable`:
```
@my.domain.org my.domain.org-%1%3
```
`name@domain` will be forwarded internally to `domain-name@domain` so that it will be handled by `aliases` appropriately. --- However, this is an ugry trick out of necessity.

---

Contemporary MTAs can handle virtual domains, thanks for the other mapping functions than `aliases`.  For example, Postfix may use virtual(5) maps and transport maps (Note that the [third excerpt](https://github.com/sympa-community/sympa/issues/739#issuecomment-526888963) does not have "`:`" separating keys and values: It is not used by `aliases` function).

IMO using Sendmail-compatible `aliases` is not recommended even if you don't need virtual domains.

**Comment by racke** [comment]
@ikedas thanks for the explanation. I will look into a more common alias template.
