### ISSUE TITLE
Change Redirect After List Admin Updates a User's Email - UX Suggestion

### ISSUE THREAD

**Issue by pkissman** [sympa-community/sympa#76]
When you use the List Administrator's ability to globally change a user's email (/serveradmin/users) it works great.
But once the update completes, you are redirected via the **move_user** action to your own preferences page (/pref).
This seems odd.  Wouldn't it make more sense to redirect either to the Listmaster Admin menu, or right back to the Listmaster Admin / Users  submenu, especially since global email changes tend to happen in batches?

**Comment by MargoM** [comment]
I would like to add, if you don't bother.

After clicking firstpasswd/renewpasswd button I receive ticket URL, where I can choosepasswd. If the inserted passwords are not same it will display error message for some seconds (example: "ERROR (setpasswd) - The passwords you typed do not match"). Now it is blank page (/wws) and I'm logged in without password, it isn't a problem. I would like to say that, maybe it would redirect to (/wws/pref) instead of showing blank page (/wws).

**Comment by ikedas** [comment]
@MargoM, please report your comment as another issue. Thanks!

**Comment by ikedas** [comment]
@pkissman, could you please check if this patch will correct problem? [patch](https://github.com/sympa-community/sympa/commit/d6c9ad738d18bca9c3e283a48635806e61c75408.patch)

**Comment by pkissman** [comment]
@ikedas , I've confirmed that the patch works.  Thanks very much.

**Comment by ikedas** [comment]
Merged. Thanks for reporting bug!
