### ISSUE TITLE
Automatic authorisation for operations (eg ADD) sent via email

### ISSUE THREAD

**Issue by aliGeeee** [sympa-community/sympa#776]
Suppose I ask Sympa to create a user through an email command like

`ADD <list> <email> <user name>`

It replies to me with an email telling me to reply in order to authorise the command:

>   You've made a user subscription request to list <list>.
If you want this action to be taken, please
reply to this mail
OR
send a message to Sympa with subject  ...... OR
click on the following mailto
If you do not want this action to be taken, you can safely ignore this message.

Is there a way to automatically perform this authentication step without having to manually reply every time I add a new subscriber? I want the whole process of adding subscribers to be done automatically through email commands and NOT the web interface.

**Comment by qosobrin** [comment]
Edit your "add" scenari. For example, suppose you have a list configure with `Add = Owner`. It translates to the following scenario:

```
title.gettext add performed by list owner does not need authentication

is_owner([listname],[sender])  smtp,dkim,md5,smime -> do_it
is_listmaster([sender])        smtp,dkim -> request_auth
is_listmaster([sender])        md5,smime -> do_it
true()                         smtp,dkim,md5,smime -> reject(reason='add_owner')
```

When the listmaster sends an user add command to a list via "regular" (no smime) e-mail it is evaluated from top to the bottom lines and it reaches these two lines:

```
is_listmaster([sender])        smtp,dkim -> request_auth
is_listmaster([sender])        md5,smime -> do_it
```

Since the request was sent by a "regular" e-mail a confirmation is sent to the listmaster as the `request_auth` action tells it to do.  You could edit this scenario changing these two lines by this one and that would do the magic you are looking for. 

```
is_listmaster([sender])        smtp,dkim,md5,smime -> do_it
```

Be aware of the security consequences of this change. Anyone could forge an e-mail sent by the listmaster and add rogue subscribers to your lists.


Mor information on scenarii customization: https://sympa-community.github.io/manual/customize/basics-scenarios.html

**Comment by ikedas** [comment]
Looks solved.  Close for now.
