### ISSUE TITLE
Q: Update language translation in Sympa 6.2 Ubuntu 18.04 package installation

### ISSUE THREAD

**Issue by billtzim** [sympa-community/sympa#796]
Hello,
i would like to update the Greek language file at a sympa 6.2.24 package installation on a ubuntu 18.04 system. I can get the el.po file from translate.sympa.org but how can i install / apply it to sympa? I cannot find any .po files in my system. Following the instructions in https://translate.sympa.org/pages/help/ did not help as it refers to installations from source

Any help / suggestions would be appreciated

**Comment by qosobrin** [comment]
First of all, I think .po files downloaded from translate.sympa.org only contain strings for the current version of Sympa (no historical strings are kept, anyone correct me if I'm wrong, please), so you're dealing with strings from a "old" version of Sympa.

I had a similar problem with my Debian Stretch 6.2.16 Sympa so I'm gonna tell you how I proceeded. 

1. Make a copy of the .mo files at your Sympa installation, in your case at `/usr/lib/sympa/locale/el/LC_MESSAGES`, to your working directory.
2. Convert those files to a user editable .po file with the following command:
```msgunfmt [path_to_file.mo] > [path_to_file.po]```
3. Edit the resulting .po files to change whatever you need to change.
4. Convert back those .po files to .mo with the command:
```msgfmt [path_to_file.po] -o [path_to_file.mo]```
5. Move those files to the Sympa language directory `/usr/lib/sympa/locale/el/LC_MESSAGES` keeping a copy of the original files just in case anything wrong happens.
6. Restart sympa and apache2 services.

Now, your Sympa installation should be using your corrected files. This is the simple version of what I did. In my case I wanted to incorporate those already translated strings in translate.sympa.org into my Sympa installation (only those that were present in both the current version and 6.2.16) so I had to combine several gettex commands to perform my goal. Unfortunatelly I did not keep a copy of what I did.

For cases like this and the one I had it would be very useful my previous feature request #182 given the fact that you only would had to download the translations file into the robot custom translastion directory and these strings would always be used instead of the ones in the dist files.

**Comment by billtzim** [comment]
Thank you very much for your help, the instructions you gave were spot on.
