### ISSUE TITLE
scenario default action

### ISSUE THREAD

**Issue by bruncsak** [sympa-community/sympa#803]
What is the default action when no condition match in a scenario?

At this moment the default/scenari/create_list.listmaster contains:

``title.gettext restricted to listmaster``

``is_listmaster([sender])                 md5,smime -> do_it``
``true()                    		smtp,md5,smime -> reject(reason='create_list_listmaster')``

Supposedly the ``true()`` condition does not match when I am arriving with ``dkim`` authentication method. What action will happen, and what action supposed to happen?

**Comment by ikedas** [comment]
Looks similar to #775 .

**Comment by bruncsak** [comment]
Dear @ikedas,

Just for the shake of completeness. The command:
``cat default/scenari/*|awk '$1 !~ /^(title\.gettext|#)?$/ {print $(NF-2)}'|sort|uniq -c``
gives:
     19 dkim,md5,smime
     49 md5,smime
     12 smime
     16 smime,md5
     19 smtp
     24 smtp,dkim
      2 smtp,dkim,md5
    163 smtp,dkim,md5,smime
     44 smtp,dkim,smime,md5
      4 smtp,md5,smime

Out of that the last (with 4 occurences) is the interesting, they are in:

default/scenari/create_list.intranet
default/scenari/create_list.listmaster
default/scenari/create_list.public_listmaster
default/scenari/del.owner

**Comment by ikedas** [comment]
I tried with 6.2.48:
``` bash
$ cat default/scenari/* | sed -ne 's/.*[ \t]\([^ \t][^ \t]*\)[ \t]*->.*/\1/p' | sort | uniq -c
     19 dkim,md5,smime
     49 md5,smime
     12 smime
     16 smime,md5
     20 smtp
     23 smtp,dkim
      2 smtp,dkim,md5
    152 smtp,dkim,md5,smime
     43 smtp,dkim,smime,md5
     20 smtp,md5,smime
      1 smtp,smime,md5
```
and also found a few:

`smtp`:
  - `default/scenari/send.ownerauth` (-)

` smtp,md5,smime`:
  - `default/scenari/create_list.intranet` (*)
  - `default/scenari/create_list.listmaster` (*)
  - `default/scenari/create_list.public_listmaster` (*)
  - `default/scenari/del.owner` (*)
  - `default/scenari/info.conceal` (-)
  - `default/scenari/info.open` (-)
  - `default/scenari/info.private` (-)
  - `default/scenari/send.owner` (-)
  - `default/scenari/send.ownerauth` (-)
  - `default/scenari/subscribe.intranetorowner`
  - `default/scenari/visibility.intranet`

`smtp,smime,md5`:
  - `default/scenari/send.owner` (-)

(-): Fixed by #775 .
(*) Pointed out by @bruncsak.

**Comment by ikedas** [comment]
I tried with
``` bash
$ cat default/scenari/* | sed -ne 's/.*[ \t]\([^ \t][^ \t]*\)[ \t]*->.*/\1/p' | sort | uniq -c
```
and these also found:

scenari/subscribe.intranetorowner
scenari/visibility.intranet

**Comment by ikedas** [comment]
Fixed.  Thanks for reporting bugs!
