### ISSUE TITLE
Email addresses

### ISSUE THREAD

**Issue by joergklein** [sympa-community/sympa#825]
The email addresses are displayed in the fields from and to. I don't think it's good for a mailing list to have email addresses public. First and last name should be visible.

**Comment by ikedas** [comment]
There are some typical use cases for mailing list service:
  1. Discussion list
       - List members can post messages. --- I.e. list members can communicate with each other.
  2. Hotline
       - Everyone, not limited to list members, may post. --- Only list members can read everything.
  3. News letter
       - Limited user(s) can post, or the list is simply moderated. --- Many specified persons only may read delivered messages.

Thus, e-mail addresses in the messages themselves _will not be made public_ by mailing list service, because they will be known only by list members (receivers).
  - With discussion list (1.) and hotline (2.), it is important among list members that they can know who originated (sent) the messages, and "From:" field shouldn't be concealed.
  - With news letter (3.), in some cases, "From:" field may be concealed. If that is the case, [`anonymous_sender`](https://sympa-community.github.io/gpldoc/man/list_config.5.html#anonymous_sender) list parameter may be used.

Messages in archives may be public, and e-mail addresses contained in them would be concealed.  If that is the case, use [`web_archive_spam_protection`](https://sympa-community.github.io/gpldoc/man/list_config.5.html#web_archive_spam_protection) parameter.

**Comment by joergklein** [comment]
All email addresses in the sympa mailing list are visible.
```
From: user.name <user@example.com>
To: user2.name2 <user.2@gmail.com>
Cc: sympa-developpers@listes.renater.fr
Subject: Re: [sympa-developpers] [sympa-announce] Sympa 6.2.49 beta 3 released
Date: Sun, 15 Dec 2019 22:53:17 +0900
```

In the kernel mailing list you see only the first and last name. 
```
Subject | Re: [PATCH 07/10] i2c: Add driver for AD242x bus controller
From | Luca Ceresoli <>
Date | Tue, 17 Dec 2019 09:35:39 +0100

```
This are enough information. The MTA knows the right email address(es).

**Comment by ikedas** [comment]
@joergklein , if you are seeing those e-mail addresses with your e-mail client, they are _not_ publicly visible: They are visible for you.  Where are you seeing "all email addresses"?

**Comment by racke** [comment]
I think @joergklein refers to the fact that the email address of the sender shows up in the list post. So instead of "From: "Stefan Hornburg (Racke)" <racke@linuxia.de>" use From: "Stefan Hornburg (Racke)" <>.

@joergklein The email address will also show in other headers.

**Comment by ikedas** [comment]
Stagnating issue.  Close for now.
