### ISSUE TITLE
t/Tools_Text.t test failing in Sympa 6.2.54

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#892]
Version
-------

6.2.54

Installation method
-------------------

Building from source

Expected behavior
-----------------

"make check" should pass all tests.

Actual behavior
---------------

One of the tests in t/Tools_Text.t fails unless the Unicode::UTF8 Perl module is installed

That is currently a  "recommends" rather than a "requires" in cpanfile.

```
#   Failed test at t/Tools_Text.t line 52.
#          got: '<U+D800>
# <U+10FFFE>
# <U+110000>
# <U+200000>
# '
#     expected: '���
# �
# ����
# �����
# '
# Looks like you failed 1 test of 13.
t/Tools_Text.t ........... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/13 subtests 
```

Additional information
----------------------

Appears to be consequence of commit 43d3041883017892e96fb2cd9979033d816c4053

I attach a minimal test script which exhibits the problem on both Ubuntu 18.04 (Perl 5.26.1) and RHEL 7 (Perl 5.16.3)

[test.pl.txt](https://github.com/sympa-community/sympa/files/4256024/test.pl.txt)

**Comment by ikedas** [comment]
Hi @dpc22 
Could you please check the PR above?

**Comment by dpc22** [comment]
That looks plausible to me if the test should only be run when the Unicode::UTF8 Perl module is installed.

I infer that the optional modules are attempting to clean up broken UTF-8? It isn't clear to me what happens with `Encode::encode_utf8($utext)` when they aren't available.

**Comment by ikedas** [comment]
https://github.com/sympa-community/sympa/blob/db8702f472b8d8a8ae9c7d18aeb4a77dd29387fe/src/lib/Sympa/Tools/Text.pm#L119-L151

As sanytization and normalization by `Unicode::UTF8` and `Unicode::Normalize` handle Unicode text, all inputs of this function have to be converted to Unicode text.
OTOH, Unicode text (utf8 flag is on) and binary text (utf8 flag is off) must not be mixed, or text will be broken. That's why the output should be binary text as the input is.  And that's why the last `Encode::encode_utf8()` is needed to convert output to binary,
