### ISSUE TITLE
Migration from Mailman

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#948]
Hello.

I am considering implementing Sympa.
However, I want to migrate my mailing list from Mailman, but I don't know how to do it and I'm at a loss.
After searching, I arrived at "https://www.sympa.org/distribution/contrib/mailman2sympa/index", but it says "This topic does not exist yet" and I can't get the script.
Is there any better way to do this?
Incidentally, the environment is Ubuntu 18.04 and Mailman 2.1.33.

Sincerely yours.

**Comment by racke** [comment]
Hello @riku22,

please checkout the following thread from the Sympa mailinglist: 

https://listes.renater.fr/sympa/arc/sympa-users/2020-05/msg00031.html

My offer to help with the migration is still valid, but I don't have a mailman instance to try with.

**Comment by riku22** [comment]
Hello.
Sorry for the late reply.
I had quite a bit of trouble, but I was able to successfully migrate from Mailman to Sympa using the method you taught me.
So, I have another question, how do I change the start number of the message?
For example, the final number of the messages in the migrated list is 500, but in Sympa I want to start at 501 instead of 1.
Could you please let me know if there is a better way to do this?
Sincerely.

**Comment by ikedas** [comment]
Hi 陸,

> So, I have another question, how do I change the start number of the message?
> For example, the final number of the messages in the migrated list is 500, but in Sympa I want to start at 501 instead of 1.
> Could you please let me know if there is a better way to do this?

Recent sequence number is saved in [`stats` file of the list](https://sympa-community.github.io/manual/customize/basics-list-config.html#other-files).  If you create or modify this file, Sympa will get the number from it (This file may contain four columns, but subsequent three columns may be omitted).

Note that the number contained in Sympa's `stats` file is the number of _the last post_, while Mailman's `post_id` is the number of _the next post_.  Thus, e.g. if the last post via Mailman list had sequene "500", `post_id`  of Mailman list may be "501", and `stats` of migrated Sympa list has to contain "500" so that the number of the next post will be "501".

**Comment by racke** [comment]
> Hello.
> Sorry for the late reply.
> I had quite a bit of trouble, but I was able to successfully migrate from Mailman to Sympa using the method you taught me.

@riku22, would you be so kind to describe your migration process from Mailman to Sympa? That would be really helpful for a lot of other users.

**Comment by riku22** [comment]
@ikedas 
ありがとうございます。
「stats」ファイルに番号を記述したところ、うまくいきました。

@racke 
https://git.fs.lmu.de/roots/mailman2sympa

First, clone the above repository.
After that, execute "import_mailman_list.sh" with the list name of the conversion source and the domain name of the conversion destination as arguments.
Basically, you can import the Mailman list with these steps.
However, because zsh is required, if you do not have it installed, you need to install it.
In my environment, if the language of Mailman uses multi-byte characters such as Japanese, the comment part of the configuration file exported by "config_list" is garbled, so use the "sed" command. Then had to delete it.
I hope this is helpful.
Sincerely.
